### ISSUE TITLE
Move from AppVeyor to Azure DevOps

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/AtlassianPS#10]
## Description

Microsoft [announced Azure DevOps](https://azure.microsoft.com/en-us/blog/introducing-azure-devops/).

More info at https://azure.microsoft.com/en-us/services/devops/

## Benefits

Azure DevOps:

* up to 10 parallel jobs
  * this allows us to run all the test jobs in parallel - as opposed to Appveyor, were each job runs after the other and can take up to 15min (JiraPS on Ubuntu)

## ToDo

* [ ] Move environment variables (including secure strings) - [link](https://dev.azure.com/AtlassianPS/ConfluencePS/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=3&view=Tab_Variables)
* [ ] Set up the dependencies of the agents:
  * have 1 build agent to build/compile the module and upload it as artifact
  * have n test agents to test the module in the artifacts
  * have 1 agent to publish module
  * [example](https://user-images.githubusercontent.com/4992870/45415514-1dfc2b00-b67e-11e8-8cf8-7c203d5040d2.png)
* [ ] have the `{build}` variable of the version be determined by `BuildHelpers\Get-NextPSGalleryVersion` - [example](https://github.com/markekraus/PSRAW/blob/staging/BuildTools/psake.ps1#L35-L54)
...

**Comment by markwragg** [comment]
As far as I've seen so far, the output of the build jobs is not public with Azure DevOps, whereas with AppVeyor anyone can see them and I think that's quite a nice thing.

Not a big deal, but unless i'm wrong something to list under shortcomings :P.

**Comment by lipkau** [comment]
I beg to differ :-)
https://dev.azure.com/AtlassianPS/AtlassianPS.Configuration/AtlassianPS.Configuration%20Team/_build/results?buildId=35

also: see badge at https://github.com/AtlassianPS/AtlassianPS.Configuration

**Comment by markwragg** [comment]
Nice! Must have been just a specific case of locked down permissions where I saw it then.
